<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

    }

    protected $fillable = [
        'booking_time',
        'package_id',
        'name',
        'email',
        'phone_number',
        'type',
        'chek_in_date',
        'chek_out_date',
        'people_no',
        'child_no',
        'total_actual_amount',
        'offered_payable_amount'
    ];

}
